
import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Veículos', icon: '🚗' },
  { id: '2', name: 'Tecnologia', icon: '💻' },
  { id: '3', name: 'Eletrodomésticos', icon: '🍳' },
  { id: '4', name: 'Esportes', icon: '⚽' },
  { id: '5', name: 'Moda', icon: '👕' },
  { id: '6', name: 'Ferramentas', icon: '🔧' },
  { id: '7', name: 'Imóveis', icon: '🏠' },
  { id: '8', name: 'Brinquedos', icon: '🧸' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'iPhone 15 Pro Max 256GB Titanium Blue',
    price: 8499.00,
    description: 'O iPhone mais potente de todos os tempos. Titanium design, chip A17 Pro, sistema de câmera Pro.',
    category: 'Tecnologia',
    image: 'https://picsum.photos/seed/iphone15/400/400',
    rating: 4.9,
    reviewsCount: 1250,
    condition: 'new',
    freeShipping: true,
    fullDelivery: true,
  },
  {
    id: 'p2',
    title: 'Monitor Gamer Curvo 34" Ultrawide 144Hz',
    price: 2850.50,
    description: 'Imersão total para seus jogos com resolução QHD e tempo de resposta de 1ms.',
    category: 'Tecnologia',
    image: 'https://picsum.photos/seed/monitor/400/400',
    rating: 4.7,
    reviewsCount: 450,
    condition: 'new',
    freeShipping: true,
    isFlashDeal: true,
  },
  {
    id: 'p3',
    title: 'Tênis Running Ultraboost 22 Masculino',
    price: 799.90,
    description: 'Conforto inigualável para suas corridas diárias com tecnologia de amortecimento Boost.',
    category: 'Esportes',
    image: 'https://picsum.photos/seed/sneakers/400/400',
    rating: 4.8,
    reviewsCount: 890,
    condition: 'new',
    freeShipping: false,
  },
  {
    id: 'p4',
    title: 'Cafeteira Expresso Automática com Moedor',
    price: 1599.00,
    description: 'Café moído na hora com o toque de um botão. Design elegante e durabilidade.',
    category: 'Eletrodomésticos',
    image: 'https://picsum.photos/seed/coffee/400/400',
    rating: 4.6,
    reviewsCount: 230,
    condition: 'new',
    freeShipping: true,
    fullDelivery: true,
  },
  {
    id: 'p5',
    title: 'Violão Elétrico Cordas de Aço Profissional',
    price: 1200.00,
    description: 'Sonoridade brilhante e acabamento de alto luxo. Ideal para palcos e estúdio.',
    category: 'Música',
    image: 'https://picsum.photos/seed/guitar/400/400',
    rating: 4.5,
    reviewsCount: 120,
    condition: 'new',
    freeShipping: true,
  },
  {
    id: 'p6',
    title: 'Câmera Mirrorless 4K 24MP Kit Lente 18-55mm',
    price: 4900.00,
    description: 'Vídeos cinematográficos e fotos nítidas com foco automático ultra rápido.',
    category: 'Tecnologia',
    image: 'https://picsum.photos/seed/camera/400/400',
    rating: 4.9,
    reviewsCount: 65,
    condition: 'new',
    freeShipping: true,
    fullDelivery: true,
  }
];
